# ============================
# Frontend Deployment
# ============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamevault-frontend
  namespace: gamevault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gamevault-frontend
  template:
    metadata:
      labels:
        app: gamevault-frontend
    spec:
      containers:
        - name: frontend
          image: ${DOCKER_REGISTRY}/frontend:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"

---
# ============================
# Frontend Service (NodePort)
# ============================
apiVersion: v1
kind: Service
metadata:
  name: gamevault-frontend
  namespace: gamevault
spec:
  type: NodePort
  selector:
    app: gamevault-frontend
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30130
